apiVersion: v1
kind: PersistentVolume
metadata:
 name: registry-volume
spec:
 accessModes:
 - ReadWriteMany
 capacity:
   storage: 15Gi
 nfs:
   path: /srv/nfs/pvs/registry-storage
   server: support1.d3fd.internal
 persistentVolumeReclaimPolicy: Retain
